/**
 * Subagent definition files — single owner of agents/*.md CRUD.
 *
 * Stores (mirrors lib/first-party/subagents/catalog.ts discovery):
 *   builtin: ~/.raincode/agents/<name>.md   (managed via pi_web_managed,
 *            regenerated by lib/ensure-subagent-delegation.ts — read-only here)
 *   user:    ~/.raincode/agents/<name>.md   (custom, no managed key)
 *   project: <cwd>/.pi/agents/<name>.md     (overrides user by file name)
 *
 * The runtime (catalog.loadAgentTypes) re-reads on every spawn, so file edits
 * take effect immediately. SDK-free: safe to import from light-runtime routes.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "fs";
import { dirname, join } from "path";
import { getAgentDir } from "./agent-dir";

/** File names regenerated by ensureSubagentDelegation — the UI cannot shadow them. */
export const MANAGED_AGENT_NAMES = ["general-purpose", "Explore", "Plan", "Reviewer"] as const;

const NAME_PATTERN = /^[a-zA-Z][a-zA-Z0-9_-]{0,63}$/;

export type ToolsPreset = "all" | "readonly" | "none" | "custom";

export const READONLY_TOOL_LIST = "read, bash, grep, find, ls";

export type SubagentDefinition = {
  name: string;
  displayName: string;
  description: string;
  /** "all" | "readonly" | "none" | custom comma list */
  toolsPreset: ToolsPreset;
  tools?: string;
  systemPrompt: string;
  promptMode: "append" | "replace";
  /** "provider/modelId" or empty = inherit parent model. */
  model?: string;
  /** Replace-mode only: append project AGENTS.md context to the prompt. */
  injectAgentsMd?: boolean;
  color?: string;
  enabled?: boolean;
};

export type SubagentListItem = SubagentDefinition & {
  scope: "builtin" | "user" | "project";
  sourcePath: string;
  managed: boolean;
};

export type SubagentListResult = {
  builtin: SubagentListItem[];
  user: SubagentListItem[];
  project: SubagentListItem[];
  paths: { user: string; project?: string };
};

/** Minimal fallback info when a managed file is missing from disk. */
const BUILTIN_FALLBACK: Array<{ name: string; displayName: string; description: string; tools: string }> = [
  { name: "general-purpose", displayName: "Agent", description: "General-purpose agent for complex, multi-step work.", tools: "" },
  { name: "Explore", displayName: "Explore", description: "Fast read-only codebase exploration.", tools: READONLY_TOOL_LIST },
  { name: "Plan", displayName: "Plan", description: "Read-only implementation planning.", tools: READONLY_TOOL_LIST },
  { name: "Reviewer", displayName: "Reviewer", description: "Read-only git/patch review.", tools: READONLY_TOOL_LIST },
];

export function getUserAgentsDir(): string {
  return join(getAgentDir(), "agents");
}

export function getProjectAgentsDir(cwd: string): string {
  return join(cwd, ".pi", "agents");
}

export function getAgentsDirForScope(scope: "user" | "project", cwd: string | null | undefined): string | null {
  if (scope === "user") return getUserAgentsDir();
  return cwd ? getProjectAgentsDir(cwd) : null;
}

export function getAgentFilePath(name: string, scope: "user" | "project", cwd: string | null | undefined): string | null {
  const dir = getAgentsDirForScope(scope, cwd);
  return dir ? join(dir, `${name}.md`) : null;
}

// ── Frontmatter (minimal: key: value, ">-"/"|-" folded blocks, booleans) ────

function parseFrontmatterBlock(content: string): { frontmatter: Record<string, string>; body: string } {
  const normalized = content.replace(/\r\n/g, "\n");
  if (!normalized.startsWith("---\n")) {
    return { frontmatter: {}, body: normalized.trim() };
  }
  const end = normalized.indexOf("\n---", 4);
  if (end === -1) return { frontmatter: {}, body: "" };
  const header = normalized.slice(4, end);
  const body = normalized.slice(end + 4).replace(/^\n/, "");
  const frontmatter: Record<string, string> = {};
  const lines = header.split("\n");
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    const match = /^([a-zA-Z_][a-zA-Z0-9_]*):(.*)$/.exec(line);
    if (!match) continue;
    const key = match[1]!;
    let value = match[2]!.trim();
    if (value === ">-" || value === "|" || value === ">-2" || value === "|-" || value === ">" || value === "|") {
      const blockLines: string[] = [];
      while (i + 1 < lines.length) {
        const next = lines[i + 1]!;
        if (!/^\s+\S/.test(next)) break;
        blockLines.push(next.trim());
        i += 1;
      }
      value = blockLines.join(" ").trim();
    } else {
      value = value.replace(/^["']|["']$/g, "");
    }
    if (value) frontmatter[key] = value;
  }
  return { frontmatter, body: body.trim() };
}

function folded(key: string, value: string): string {
  return `${key}: >-\n  ${value.replace(/\s+/g, " ").trim()}`;
}

function parseToolsField(raw: string | undefined): { toolsPreset: ToolsPreset; tools?: string } {
  if (raw === undefined || raw === "") return { toolsPreset: "all" };
  const trimmed = raw.trim();
  if (!trimmed || trimmed === "none") return { toolsPreset: "none" };
  if (trimmed.replace(/\s/g, "") === READONLY_TOOL_LIST.replace(/\s/g, "")) return { toolsPreset: "readonly" };
  return { toolsPreset: "custom", tools: trimmed };
}

function definitionFromParts(name: string, frontmatter: Record<string, string>, body: string): SubagentDefinition {
  const { toolsPreset, tools } = parseToolsField(frontmatter.tools);
  return {
    name,
    displayName: frontmatter.display_name ?? name,
    description: frontmatter.description ?? "",
    toolsPreset,
    ...(tools ? { tools } : {}),
    systemPrompt: body,
    promptMode: frontmatter.prompt_mode === "replace" ? "replace" : "append",
    ...(frontmatter.model ? { model: frontmatter.model } : {}),
    ...(frontmatter.inject_agents_md === "true" ? { injectAgentsMd: true } : {}),
    ...(frontmatter.color ? { color: frontmatter.color } : {}),
    ...(frontmatter.enabled === "false" ? { enabled: false } : {}),
  };
}

function serializeAgentMarkdown(def: SubagentDefinition): string {
  const lines: string[] = ["---", `display_name: ${def.displayName || def.name}`];
  if (def.description.trim()) lines.push(folded("description", def.description));
  if (def.toolsPreset === "readonly") lines.push(`tools: ${READONLY_TOOL_LIST}`);
  else if (def.toolsPreset === "none") lines.push("tools: none");
  else if (def.toolsPreset === "custom" && def.tools?.trim()) lines.push(`tools: ${def.tools.trim()}`);
  if (def.promptMode === "replace") lines.push("prompt_mode: replace");
  if (def.model?.trim()) lines.push(`model: ${def.model.trim()}`);
  if (def.injectAgentsMd === true && def.promptMode === "replace") lines.push("inject_agents_md: true");
  if (def.color?.trim()) lines.push(`color: ${def.color.trim()}`);
  if (def.enabled === false) lines.push("enabled: false");
  lines.push("---", "", def.systemPrompt.trim(), "");
  return lines.join("\n");
}

// ── Listing ──────────────────────────────────────────────────────────────────

function listDirItems(dir: string, scope: "user" | "project", filter: (name: string) => boolean): SubagentListItem[] {
  if (!existsSync(dir)) return [];
  let files: string[] = [];
  try {
    files = readdirSync(dir).filter((name) => name.endsWith(".md"));
  } catch {
    return [];
  }
  const items: SubagentListItem[] = [];
  for (const file of files) {
    const name = file.slice(0, -3);
    if (!filter(name)) continue;
    try {
      const { frontmatter, body } = parseFrontmatterBlock(readFileSync(join(dir, file), "utf8"));
      const def = definitionFromParts(name, frontmatter, body);
      items.push({ ...def, scope, sourcePath: join(dir, file), managed: frontmatter.pi_web_managed === "true" });
    } catch {
      // Unreadable file — skip it rather than failing the whole list.
    }
  }
  return items;
}

export function listSubagents(cwd: string | null | undefined): SubagentListResult {
  const userDir = getUserAgentsDir();
  const builtin: SubagentListItem[] = [];
  for (const fallback of BUILTIN_FALLBACK) {
    const filePath = join(userDir, `${fallback.name}.md`);
    if (existsSync(filePath)) {
      try {
        const { frontmatter, body } = parseFrontmatterBlock(readFileSync(filePath, "utf8"));
        const def = definitionFromParts(fallback.name, frontmatter, body);
        builtin.push({ ...def, displayName: frontmatter.display_name ?? fallback.displayName, scope: "builtin", sourcePath: filePath, managed: true });
        continue;
      } catch {
        // fall through to fallback info
      }
    }
    builtin.push({
      name: fallback.name,
      displayName: fallback.displayName,
      description: fallback.description,
      toolsPreset: fallback.tools ? "readonly" : "all",
      ...(fallback.tools ? { tools: fallback.tools } : {}),
      systemPrompt: "",
      promptMode: "replace",
      scope: "builtin",
      sourcePath: filePath,
      managed: true,
    });
  }
  const managedSet = new Set<string>(MANAGED_AGENT_NAMES);
  const user = listDirItems(userDir, "user", (name) => !managedSet.has(name));
  const project = cwd ? listDirItems(getProjectAgentsDir(cwd), "project", (name) => !managedSet.has(name)) : [];
  return {
    builtin,
    user,
    project,
    paths: { user: userDir, ...(cwd ? { project: getProjectAgentsDir(cwd) } : {}) },
  };
}

// ── Validation + CRUD ────────────────────────────────────────────────────────

export function validateSubagentPayload(body: Record<string, unknown>, existing?: SubagentDefinition): { def: SubagentDefinition } | { error: string } {
  const name = (typeof body.name === "string" ? body.name : existing?.name ?? "").trim();
  if (!name) return { error: "name required" };
  if (!NAME_PATTERN.test(name)) {
    return { error: "name must match [a-zA-Z][a-zA-Z0-9_-]{0,63}" };
  }
  if (!existing && (MANAGED_AGENT_NAMES as readonly string[]).some((n) => n.toLowerCase() === name.toLowerCase())) {
    return { error: `"${name}" is a built-in agent name — pick another` };
  }
  const description = (typeof body.description === "string" ? body.description : "").replace(/\s+/g, " ").trim();
  if (!description) return { error: "description required" };
  if (description.length > 500) return { error: "description too long (max 500)" };
  const systemPrompt = (typeof body.systemPrompt === "string" ? body.systemPrompt : "").trim();
  if (!systemPrompt) return { error: "systemPrompt required" };
  if (systemPrompt.length > 20000) return { error: "systemPrompt too long (max 20000)" };
  const promptMode = body.promptMode === "replace" ? "replace" : "append";
  const toolsPresetRaw = typeof body.toolsPreset === "string" ? body.toolsPreset : "all";
  const toolsPreset: ToolsPreset = toolsPresetRaw === "readonly" || toolsPresetRaw === "none" || toolsPresetRaw === "custom"
    ? toolsPresetRaw
    : "all";
  let tools: string | undefined;
  if (toolsPreset === "custom") {
    tools = (typeof body.tools === "string" ? body.tools : "").split(",").map((t) => t.trim()).filter(Boolean).join(", ");
    if (!tools) return { error: "custom tools list required for toolsPreset=custom" };
    if (tools.length > 1000) return { error: "tools list too long (max 1000)" };
  }
  const model = typeof body.model === "string" ? body.model.trim() : "";
  if (model && !/^[a-zA-Z0-9._\-]+\/[a-zA-Z0-9._\-]+$/.test(model)) {
    return { error: "model must look like provider/modelId" };
  }
  const color = typeof body.color === "string" ? body.color.trim() : "";
  const def: SubagentDefinition = {
    name,
    displayName: name,
    description,
    toolsPreset,
    ...(tools ? { tools } : {}),
    systemPrompt,
    promptMode,
    ...(model ? { model } : {}),
    ...(body.injectAgentsMd === true && promptMode === "replace" ? { injectAgentsMd: true } : {}),
    ...(color ? { color } : {}),
    ...(body.enabled === false ? { enabled: false } : {}),
  };
  return { def };
}

/** Insert or replace a custom agent file. Managed names are rejected. */
export function upsertSubagent(def: SubagentDefinition, scope: "user" | "project", cwd: string | null | undefined): SubagentDefinition {
  if ((MANAGED_AGENT_NAMES as readonly string[]).some((n) => n.toLowerCase() === def.name.toLowerCase())) {
    throw Object.assign(new Error(`"${def.name}" is a built-in agent name`), { status: 400 });
  }
  const path = getAgentFilePath(def.name, scope, cwd);
  if (!path) throw Object.assign(new Error("project scope requires cwd"), { status: 400 });
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, serializeAgentMarkdown(def), "utf8");
  return def;
}

export function deleteSubagent(name: string, scope: "user" | "project", cwd: string | null | undefined): boolean {
  const path = getAgentFilePath(name, scope, cwd);
  if (!path || !existsSync(path)) return false;
  rmSync(path);
  return true;
}

export function setSubagentEnabled(
  name: string,
  enabled: boolean,
  scope: "user" | "project",
  cwd: string | null | undefined,
): SubagentDefinition | null {
  const path = getAgentFilePath(name, scope, cwd);
  if (!path || !existsSync(path)) return null;
  const { frontmatter, body } = parseFrontmatterBlock(readFileSync(path, "utf8"));
  const current = definitionFromParts(name, frontmatter, body);
  return upsertSubagent({ ...current, enabled }, scope, cwd);
}
